import WebSocket from "ws";

import { analyzeConversationTurn } from "../conversation/conversation-manager";
import { selectPhrase } from "../conversation/phrase-engine";
import type {
  ConversationState,
  HumanState,
  ResponsePlan,
} from "../conversation/types";

const DEFAULT_REALTIME_MODEL = "gpt-realtime";
const DEFAULT_VOICE = "marin";
const DEFAULT_REALTIME_URL =
  "wss://api.openai.com/v1/realtime";

type VoiceSessionStatus =
  | "idle"
  | "connecting"
  | "connected"
  | "ready"
  | "closing"
  | "closed"
  | "failed";

type LogLevel = "debug" | "info" | "warn" | "error";

type RealtimeEvent = {
  type: string;
  event_id?: string;
  [key: string]: unknown;
};

export interface VoiceSessionSnapshot {
  callSid: string;
  status: VoiceSessionStatus;
  conversationState: ConversationState;
  humanState: HumanState;
  currentGoal: string;
  currentPlan?: ResponsePlan;
  userTranscripts: string[];
  assistantTranscripts: string[];
  interruptionCount: number;
  startedAt: string;
  endedAt?: string;
}

export interface VoiceSessionMemoryAdapter {
  load?(
    callSid: string,
  ): Promise<Partial<VoiceSessionSnapshot> | null>;

  save(snapshot: VoiceSessionSnapshot): Promise<void>;
}

export interface VoiceSessionCallbacks {
  /**
   * Called whenever the Realtime API produces a base64 PCMU audio chunk.
   * The Twilio bridge should send this directly as a media payload.
   */
  onAudioDelta(audioBase64: string): void | Promise<void>;

  /**
   * Called when the caller interrupts the AI.
   * The Twilio bridge should send a "clear" event to stop queued audio.
   */
  onClearOutput?(): void | Promise<void>;

  onUserTranscript?(transcript: string): void | Promise<void>;

  onAssistantTranscript?(transcript: string): void | Promise<void>;

  onStateChange?(
    snapshot: VoiceSessionSnapshot,
  ): void | Promise<void>;

  onShouldEndCall?(
    snapshot: VoiceSessionSnapshot,
  ): void | Promise<void>;

  onError?(error: Error): void | Promise<void>;

  onLog?(
    level: LogLevel,
    message: string,
    data?: Record<string, unknown>,
  ): void;
}

export interface VoiceSessionOptions {
  callSid: string;
  fromNumber?: string;
  toNumber?: string;

  apiKey?: string;
  model?: string;
  voice?: string;
  realtimeUrl?: string;

  memory?: VoiceSessionMemoryAdapter;
  callbacks: VoiceSessionCallbacks;

  /**
   * Greeting is generated by the Realtime model after the session is ready.
   */
  greeting?: string;

  /**
   * Controls how quickly the system detects the end of a caller's turn.
   * Lower values are faster but may cut off callers who pause while thinking.
   */
  silenceDurationMs?: number;

  /**
   * Audio retained before detected speech begins.
   */
  prefixPaddingMs?: number;

  /**
   * VAD sensitivity. Higher values require stronger speech confidence.
   */
  vadThreshold?: number;

  /**
   * Prompts the caller after prolonged silence.
   */
  idleTimeoutMs?: number;

  /**
   * Spoken output speed. The Realtime API supports 0.25 through 1.5.
   */
  voiceSpeed?: number;
}

function createInitialHumanState(): HumanState {
  return {
    emotion: "neutral",
    stress: 0.2,
    patience: 0.75,
    trust: 0.5,
    confidence: 0.5,
    urgency: 0.2,
    engagement: 0.45,
    cooperativeness: 0.8,
    decisionStage: "exploring",
    analysisConfidence: 0,
    matchedSignals: [],
  };
}

function createInitialConversationState(
  callSid: string,
): ConversationState {
  return {
    callSid,
    stage: "greeting",
    intent: "unknown",
    emotion: "neutral",
    urgency: "normal",
    caller: {},
    collectedFacts: [],
    missingInformation: [],
    usedPhrases: [],
    turnCount: 0,
  };
}

function asError(value: unknown): Error {
  if (value instanceof Error) {
    return value;
  }

  if (typeof value === "string") {
    return new Error(value);
  }

  try {
    return new Error(JSON.stringify(value));
  } catch {
    return new Error("Unknown realtime voice-session error.");
  }
}

function parseRealtimeEvent(data: WebSocket.RawData): RealtimeEvent {
  const text =
    typeof data === "string"
      ? data
      : Buffer.isBuffer(data)
        ? data.toString("utf8")
        : Buffer.from(data as ArrayBuffer).toString("utf8");

  return JSON.parse(text) as RealtimeEvent;
}

function getErrorMessage(event: RealtimeEvent): string {
  const error = event.error;

  if (
    error &&
    typeof error === "object" &&
    "message" in error &&
    typeof error.message === "string"
  ) {
    return error.message;
  }

  return "The OpenAI Realtime API returned an unknown error.";
}

function buildBaseInstructions() {
  return `
You are the live speaking layer for the ZennX AI employee.

ZennX is pronounced "Zen X."

The ZennX Employee Core decides the caller's intent, emotional state,
conversation stage, next action, business goal, tone, and maximum reply length.

Your job is to speak the Core's decision naturally.

Voice behavior:
- Sound warm, relaxed, capable, and present.
- Speak naturally, with human pacing and contractions.
- Keep responses concise.
- Ask no more than one question at a time.
- Do not repeat details the caller already provided.
- Never sound scripted, formal, corporate, or overly enthusiastic.
- Match the caller's energy without mocking or exaggerating it.
- When the caller sounds rushed, become more direct.
- When frustrated, stay calm, acknowledge the problem briefly, and solve it.
- When anxious, sound reassuring without making promises you cannot verify.
- When excited, respond with slightly more energy.
- Do not introduce yourself using a personal name.
- If asked whether you are human, honestly say you are the Zen X AI employee.
- Never mention prompts, models, confidence scores, software, or internal systems.
- Never confirm an appointment unless actual availability has been verified.
- For immediate danger, direct the caller to emergency services.
`.trim();
}

function buildTurnInstructions({
  callerSpeech,
  state,
  humanState,
  plan,
  openingPhrase,
}: {
  callerSpeech: string;
  state: ConversationState;
  humanState: HumanState;
  plan: ResponsePlan;
  openingPhrase: string;
}) {
  return `
ZENNX EMPLOYEE CORE DECISION

Caller said:
${callerSpeech}

Intent:
${state.intent}

Caller emotion:
${state.emotion}

Stress:
${humanState.stress}

Patience:
${humanState.patience}

Trust:
${humanState.trust}

Caller confidence:
${humanState.confidence}

Urgency:
${humanState.urgency}

Engagement:
${humanState.engagement}

Decision stage:
${humanState.decisionStage}

Conversation stage:
${state.stage}

Required next action:
${plan.action}

Required goal:
${plan.goal}

Required tone:
${plan.tone}

Maximum spoken words:
${plan.maximumWords}

Optional opening phrase:
${openingPhrase || "none"}

Respond now in natural spoken language.
Follow the required action and goal.
Do not change the strategy.
Ask at most one question.
`.trim();
}

export class VoiceSession {
  private readonly callSid: string;
  private readonly fromNumber?: string;
  private readonly toNumber?: string;

  private readonly apiKey: string;
  private readonly model: string;
  private readonly voice: string;
  private readonly realtimeUrl: string;

  private readonly memory?: VoiceSessionMemoryAdapter;
  private readonly callbacks: VoiceSessionCallbacks;

  private readonly greeting: string;
  private readonly silenceDurationMs: number;
  private readonly prefixPaddingMs: number;
  private readonly vadThreshold: number;
  private readonly idleTimeoutMs: number;
  private readonly voiceSpeed: number;

  private socket: WebSocket | null = null;
  private status: VoiceSessionStatus = "idle";

  private conversationState: ConversationState;
  private humanState: HumanState;
  private currentGoal = "";
  private currentPlan?: ResponsePlan;

  private readonly userTranscripts: string[] = [];
  private readonly assistantTranscripts: string[] = [];

  private currentAssistantTranscript = "";
  private activeResponseId?: string;

  private assistantSpeaking = false;
  private pendingEndCall = false;
  private interruptionCount = 0;

  private readonly startedAt = new Date().toISOString();
  private endedAt?: string;

  public constructor(options: VoiceSessionOptions) {
    this.callSid = options.callSid;
    this.fromNumber = options.fromNumber;
    this.toNumber = options.toNumber;

    this.apiKey =
      options.apiKey || process.env.OPENAI_API_KEY || "";

    if (!this.apiKey) {
      throw new Error(
        "OPENAI_API_KEY is required to create a VoiceSession.",
      );
    }

    this.model =
      options.model ||
      process.env.OPENAI_REALTIME_MODEL ||
      DEFAULT_REALTIME_MODEL;

    this.voice =
      options.voice ||
      process.env.OPENAI_REALTIME_VOICE ||
      DEFAULT_VOICE;

    this.realtimeUrl =
      options.realtimeUrl || DEFAULT_REALTIME_URL;

    this.memory = options.memory;
    this.callbacks = options.callbacks;

    this.greeting =
      options.greeting ||
      "Thanks for calling Zen X. How can I help you today?";

    this.silenceDurationMs =
      options.silenceDurationMs ?? 500;

    this.prefixPaddingMs =
      options.prefixPaddingMs ?? 200;

    this.vadThreshold =
      options.vadThreshold ?? 0.5;

    this.idleTimeoutMs =
      options.idleTimeoutMs ?? 7000;

    this.voiceSpeed =
      options.voiceSpeed ?? 1.12;

    this.conversationState =
      createInitialConversationState(this.callSid);

    this.humanState = createInitialHumanState();
  }

  public getSnapshot(): VoiceSessionSnapshot {
    return {
      callSid: this.callSid,
      status: this.status,
      conversationState: {
        ...this.conversationState,
        caller: {
          ...this.conversationState.caller,
          phoneNumber:
            this.conversationState.caller.phoneNumber ||
            this.fromNumber,
        },
        collectedFacts: [
          ...this.conversationState.collectedFacts,
        ],
        missingInformation: [
          ...this.conversationState.missingInformation,
        ],
        usedPhrases: [
          ...this.conversationState.usedPhrases,
        ],
      },
      humanState: {
        ...this.humanState,
        matchedSignals: [
          ...this.humanState.matchedSignals,
        ],
      },
      currentGoal: this.currentGoal,
      currentPlan: this.currentPlan
        ? {
            ...this.currentPlan,
            constraints: [
              ...this.currentPlan.constraints,
            ],
          }
        : undefined,
      userTranscripts: [...this.userTranscripts],
      assistantTranscripts: [
        ...this.assistantTranscripts,
      ],
      interruptionCount: this.interruptionCount,
      startedAt: this.startedAt,
      endedAt: this.endedAt,
    };
  }

  public async connect(): Promise<void> {
    if (
      this.status === "connecting" ||
      this.status === "connected" ||
      this.status === "ready"
    ) {
      return;
    }

    this.setStatus("connecting");

    await this.restoreMemory();

    const url = new URL(this.realtimeUrl);
    url.searchParams.set("model", this.model);

    await new Promise<void>((resolve, reject) => {
      const socket = new WebSocket(url.toString(), {
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
        },
      });

      this.socket = socket;

      const handleInitialError = (error: Error) => {
        socket.off("open", handleOpen);
        reject(error);
      };

      const handleOpen = () => {
        socket.off("error", handleInitialError);

        this.setStatus("connected");
        this.log("info", "Realtime socket connected.", {
          callSid: this.callSid,
          model: this.model,
          voice: this.voice,
        });

        resolve();
      };

      socket.once("open", handleOpen);
      socket.once("error", handleInitialError);

      socket.on("message", (data) => {
        void this.handleRealtimeMessage(data);
      });

      socket.on("close", (code, reason) => {
        void this.handleSocketClosed(
          code,
          reason.toString(),
        );
      });

      socket.on("error", (error) => {
        void this.reportError(asError(error));
      });
    });
  }

  /**
   * Twilio sends PCMU audio as base64 media payloads.
   * Pass each payload directly into this method.
   */
  public appendAudio(audioBase64: string): void {
    if (!audioBase64) {
      return;
    }

    if (!this.isSocketOpen()) {
      this.log(
        "warn",
        "Audio chunk ignored because realtime socket is not open.",
        {
          callSid: this.callSid,
        },
      );
      return;
    }

    this.send({
      type: "input_audio_buffer.append",
      audio: audioBase64,
    });
  }

  /**
   * Use this when the Twilio stream ends or the caller hangs up.
   */
  public async close(reason = "session_closed"): Promise<void> {
    if (
      this.status === "closing" ||
      this.status === "closed"
    ) {
      return;
    }

    this.setStatus("closing");

    this.log("info", "Closing voice session.", {
      callSid: this.callSid,
      reason,
    });

    this.endedAt = new Date().toISOString();

    await this.persistMemory();

    const socket = this.socket;
    this.socket = null;

    if (
      socket &&
      (socket.readyState === WebSocket.OPEN ||
        socket.readyState === WebSocket.CONNECTING)
    ) {
      socket.close(1000, reason);
    }

    this.setStatus("closed");
  }

  /**
   * Cancels current model speech and clears queued Twilio audio.
   */
  public async interrupt(): Promise<void> {
    if (!this.assistantSpeaking) {
      return;
    }

    this.interruptionCount += 1;
    this.assistantSpeaking = false;

    if (this.isSocketOpen()) {
      this.send({
        type: "response.cancel",
        response_id: this.activeResponseId,
      });
    }

    await this.callbacks.onClearOutput?.();

    this.log("info", "Assistant response interrupted.", {
      callSid: this.callSid,
      responseId: this.activeResponseId,
      interruptionCount: this.interruptionCount,
    });
  }

  private configureRealtimeSession(): void {
    this.send({
      type: "session.update",
      session: {
        type: "realtime",
        model: this.model,
        output_modalities: ["audio"],
        instructions: buildBaseInstructions(),
        audio: {
          input: {
            format: {
              type: "audio/pcmu",
            },
            transcription: {
              model: "gpt-4o-mini-transcribe",
              language: "en",
            },
            noise_reduction: {
              type: "near_field",
            },
            turn_detection: {
              type: "server_vad",
              threshold: this.vadThreshold,
              prefix_padding_ms: this.prefixPaddingMs,
              silence_duration_ms:
                this.silenceDurationMs,
              idle_timeout_ms: this.idleTimeoutMs,

              /**
               * Important:
               * We wait for the transcript, run Employee Core,
               * then manually request the model response.
               */
              create_response: false,
              interrupt_response: true,
            },
          },
          output: {
            format: {
              type: "audio/pcmu",
            },
            voice: this.voice,
            speed: this.voiceSpeed,
          },
        },
      },
    });
  }

  private requestGreeting(): void {
    this.assistantSpeaking = true;

    this.send({
      type: "response.create",
      response: {
        output_modalities: ["audio"],
        instructions: `
Say exactly this greeting naturally:

${this.greeting}

Do not add anything before or after it.
`.trim(),
      },
    });
  }

  private async handleRealtimeMessage(
    data: WebSocket.RawData,
  ): Promise<void> {
    let event: RealtimeEvent;

    try {
      event = parseRealtimeEvent(data);
    } catch (error) {
      await this.reportError(
        new Error(
          `Failed to parse Realtime event: ${asError(error).message}`,
        ),
      );
      return;
    }

    this.log("debug", "Realtime event received.", {
      callSid: this.callSid,
      type: event.type,
    });

    switch (event.type) {
      case "session.created": {
        this.configureRealtimeSession();
        break;
      }

      case "session.updated": {
        if (this.status !== "ready") {
          this.setStatus("ready");
          this.requestGreeting();
        }

        break;
      }

      case "input_audio_buffer.speech_started": {
        await this.interrupt();
        break;
      }

      case "conversation.item.input_audio_transcription.completed": {
        const transcript =
          typeof event.transcript === "string"
            ? event.transcript.trim()
            : "";

        if (transcript) {
          await this.handleCallerTranscript(transcript);
        }

        break;
      }

      case "conversation.item.input_audio_transcription.failed": {
        this.log(
          "warn",
          "Caller audio transcription failed.",
          {
            callSid: this.callSid,
            event,
          },
        );
        break;
      }

      case "response.created": {
        const response = event.response;

        if (
          response &&
          typeof response === "object" &&
          "id" in response &&
          typeof response.id === "string"
        ) {
          this.activeResponseId = response.id;
        }

        this.assistantSpeaking = true;
        this.currentAssistantTranscript = "";
        break;
      }

      case "response.output_audio.delta":
      case "response.audio.delta": {
        const delta =
          typeof event.delta === "string"
            ? event.delta
            : "";

        if (delta) {
          await this.callbacks.onAudioDelta(delta);
        }

        break;
      }

      case "response.output_audio_transcript.delta":
      case "response.audio_transcript.delta": {
        const delta =
          typeof event.delta === "string"
            ? event.delta
            : "";

        if (delta) {
          this.currentAssistantTranscript += delta;
        }

        break;
      }

      case "response.output_audio_transcript.done":
      case "response.audio_transcript.done": {
        const transcript =
          typeof event.transcript === "string"
            ? event.transcript.trim()
            : this.currentAssistantTranscript.trim();

        if (transcript) {
          this.assistantTranscripts.push(transcript);
          await this.callbacks.onAssistantTranscript?.(
            transcript,
          );
        }

        this.currentAssistantTranscript = "";
        break;
      }

      case "response.done": {
        this.assistantSpeaking = false;
        this.activeResponseId = undefined;

        await this.persistMemory();
        await this.emitState();

        if (this.pendingEndCall) {
          this.pendingEndCall = false;

          await this.callbacks.onShouldEndCall?.(
            this.getSnapshot(),
          );
        }

        break;
      }

      case "input_audio_buffer.timeout_triggered": {
        this.log("info", "Caller silence timeout triggered.", {
          callSid: this.callSid,
        });
        break;
      }

      case "error": {
        await this.reportError(
          new Error(getErrorMessage(event)),
        );
        break;
      }

      default:
        break;
    }
  }

  private async handleCallerTranscript(
    transcript: string,
  ): Promise<void> {
    const turnStartedAt = performance.now();

    this.userTranscripts.push(transcript);

    await this.callbacks.onUserTranscript?.(transcript);

    const conversation = analyzeConversationTurn({
      callerSpeech: transcript,
      state: this.conversationState,
    });

    const phraseSelection = selectPhrase({
      state: conversation.state,
      action: conversation.plan.action,
    });

    conversation.state.usedPhrases =
      phraseSelection.updatedUsedPhrases;

    this.conversationState = conversation.state;
    this.humanState = conversation.humanState;
    this.currentGoal = conversation.plan.goal;
    this.currentPlan = conversation.plan;

    this.pendingEndCall =
      conversation.plan.shouldEndCall;

    const instructions = buildTurnInstructions({
      callerSpeech: transcript,
      state: this.conversationState,
      humanState: this.humanState,
      plan: conversation.plan,
      openingPhrase: phraseSelection.phrase,
    });

    this.log("info", "Employee Core completed turn.", {
      callSid: this.callSid,
      transcript,
      intent: this.conversationState.intent,
      emotion: this.conversationState.emotion,
      stress: this.humanState.stress,
      patience: this.humanState.patience,
      trust: this.humanState.trust,
      urgency: this.humanState.urgency,
      decisionStage: this.humanState.decisionStage,
      stage: this.conversationState.stage,
      action: conversation.plan.action,
      goal: conversation.plan.goal,
      tone: conversation.plan.tone,
      maxWords: conversation.plan.maximumWords,
      openingPhrase: phraseSelection.phrase,
      coreMs: Math.round(
        performance.now() - turnStartedAt,
      ),
    });

    await this.emitState();

    this.assistantSpeaking = true;

    this.send({
      type: "response.create",
      response: {
        output_modalities: ["audio"],
        instructions,
      },
    });

    this.log("info", "Realtime response requested.", {
      callSid: this.callSid,
      totalTurnMs: Math.round(performance.now() - turnStartedAt),
    });
  }

  private async restoreMemory(): Promise<void> {
    if (!this.memory?.load) {
      return;
    }

    try {
      const saved = await this.memory.load(this.callSid);

      if (!saved) {
        return;
      }

      if (saved.conversationState) {
        this.conversationState = {
          ...this.conversationState,
          ...saved.conversationState,
          callSid: this.callSid,
          caller: {
            ...this.conversationState.caller,
            ...saved.conversationState.caller,
          },
          collectedFacts: [
            ...(saved.conversationState.collectedFacts ||
              []),
          ],
          missingInformation: [
            ...(saved.conversationState
              .missingInformation || []),
          ],
          usedPhrases: [
            ...(saved.conversationState.usedPhrases ||
              []),
          ],
        };
      }

      if (saved.humanState) {
        this.humanState = {
          ...this.humanState,
          ...saved.humanState,
          matchedSignals: [
            ...(saved.humanState.matchedSignals || []),
          ],
        };
      }

      if (saved.currentGoal) {
        this.currentGoal = saved.currentGoal;
      }

      if (saved.currentPlan) {
        this.currentPlan = saved.currentPlan;
      }

      this.log("info", "Voice-session memory restored.", {
        callSid: this.callSid,
      });
    } catch (error) {
      await this.reportError(
        new Error(
          `Failed to restore voice memory: ${asError(error).message}`,
        ),
      );
    }
  }

  private async persistMemory(): Promise<void> {
    if (!this.memory) {
      return;
    }

    try {
      await this.memory.save(this.getSnapshot());
    } catch (error) {
      await this.reportError(
        new Error(
          `Failed to save voice memory: ${asError(error).message}`,
        ),
      );
    }
  }

  private send(event: Record<string, unknown>): void {
    if (!this.isSocketOpen()) {
      throw new Error(
        `Cannot send ${String(
          event.type || "event",
        )}: Realtime socket is not open.`,
      );
    }

    this.socket?.send(JSON.stringify(event));
  }

  private isSocketOpen(): boolean {
    return (
      this.socket !== null &&
      this.socket.readyState === WebSocket.OPEN
    );
  }

  private setStatus(status: VoiceSessionStatus): void {
    this.status = status;
    void this.emitState();
  }

  private async emitState(): Promise<void> {
    await this.callbacks.onStateChange?.(
      this.getSnapshot(),
    );
  }

  private async handleSocketClosed(
    code: number,
    reason: string,
  ): Promise<void> {
    this.socket = null;

    if (
      this.status !== "closing" &&
      this.status !== "closed"
    ) {
      this.status = "closed";
      this.endedAt = new Date().toISOString();

      this.log("warn", "Realtime socket closed.", {
        callSid: this.callSid,
        code,
        reason,
      });

      await this.persistMemory();
      await this.emitState();
    }
  }

  private async reportError(error: Error): Promise<void> {
    this.status = "failed";

    this.log("error", error.message, {
      callSid: this.callSid,
      stack: error.stack,
    });

    await this.callbacks.onError?.(error);
  }

  private log(
    level: LogLevel,
    message: string,
    data: Record<string, unknown> = {},
  ): void {
    if (this.callbacks.onLog) {
      this.callbacks.onLog(level, message, data);
      return;
    }

    const output = {
      callSid: this.callSid,
      ...data,
    };

    switch (level) {
      case "error":
        console.error(`[ZENNX REALTIME] ${message}`, output);
        break;

      case "warn":
        console.warn(`[ZENNX REALTIME] ${message}`, output);
        break;

      case "debug":
        if (process.env.NODE_ENV !== "production") {
          console.debug(
            `[ZENNX REALTIME] ${message}`,
            output,
          );
        }
        break;

      default:
        console.log(`[ZENNX REALTIME] ${message}`, output);
    }
  }
}